using FamicomSimulator.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace FamicomSimulator.Core
{
    internal struct OpConfig
    { 
        public string Name;
        public byte Opcode;
        public Instruction Instruction;
        public AddressingMode AddressingMode;
        private string _internalName;

        public OpConfig(string name, byte opcode)
        {
            _internalName = name;
            Opcode = opcode;
            Name = name[..3];
            if (!Enum.TryParse<Instruction>(name[..3], out Instruction))
            {
                LogUtil.Error($"未处理的指令 name:{name} opcode:{opcode:X2}");
            }
            if (name.Length > 3)
            {
                AddressingMode = AssembleCode.AddressingModePattern[name[3..].Trim()];
            }
            else
            {
                AddressingMode = AddressingMode.Implicit;
            }
        }
    }

    internal static class AssembleCode
    {
        internal static Dictionary<string, AddressingMode> AddressingModePattern = new Dictionary<string, AddressingMode>()
        {
            {"", AddressingMode.Implicit},
            {"#i", AddressingMode.Immediate},
            {"d", AddressingMode.ZeroPage},
            {"d,x", AddressingMode.ZeroPageX},
            {"d,y", AddressingMode.ZeroPageY},
            {"a", AddressingMode.Absolute},
            {"a,x", AddressingMode.AbsoluteX},
            {"a,y", AddressingMode.AbsoluteY},
            {"(d,x)", AddressingMode.IndirectX},
            {"(d),y", AddressingMode.IndirectY},
            {"*+d", AddressingMode.Relative},
            {"A", AddressingMode.Accumulator},
            {"(a)", AddressingMode.Indirect},
        };

        internal static OpConfig[] OpCodeArrangement = new OpConfig[256]
        {
            // $00
            new("BRK", 0x00),
            new("ORA (d,x)", 0x01),
            new("STP", 0x02),
            new("SLO (d,x)", 0x03),
            new("NOP d", 0x04),
            new("ORA d", 0x05),
            new("ASL d", 0x06),
            new("SLO d", 0x07),
            new("PHP", 0x08),
            new("ORA #i", 0x09),
            new("ASL A", 0x0A),
            new("ANC #i", 0x0B),
            new("NOP a", 0x0C),
            new("ORA a", 0x0D),
            new("ASL a", 0x0E),
            new("SLO a", 0x0F),
            // $10
            new("BPL *+d", 0x10),
            new("ORA (d),y", 0x11),
            new("STP", 0x12),
            new("SLO (d),y", 0x13),
            new("NOP d,x", 0x14),
            new("ORA d,x", 0x15),
            new("ASL d,x", 0x16),
            new("SLO d,x", 0x17),
            new("CLC", 0x18),
            new("ORA a,y", 0x19),
            new("NOP", 0x1A),
            new("SLO a,y", 0x1B),
            new("NOP a,x", 0x1C),
            new("ORA a,x", 0x1D),
            new("ASL a,x", 0x1E),
            new("SLO a,x", 0x1F),
            // $20
            new("JSR a", 0x20),
            new("AND (d,x)", 0x21),
            new("STP", 0x22),
            new("RLA (d,x)", 0x23),
            new("BIT d", 0x24),
            new("AND d", 0x25),
            new("ROL d", 0x26),
            new("RLA d", 0x27),
            new("PLP", 0x28),
            new("AND #i", 0x29),
            new("ROL A", 0x2A),
            new("ANC #i", 0x2B),
            new("BIT a", 0x2C),
            new("AND a", 0x2D),
            new("ROL a", 0x2E),
            new("RLA a", 0x2F),
            // $30
            new("BMI *+d", 0x30),
            new("AND (d),y", 0x31),
            new("STP", 0x32),
            new("RLA (d),y", 0x33),
            new("NOP d,x", 0x34),
            new("AND d,x", 0x35),
            new("ROL d,x", 0x36),
            new("RLA d,x", 0x37),
            new("SEC", 0x38),
            new("AND a,y", 0x39),
            new("NOP", 0x3A),
            new("RLA a,y", 0x3B),
            new("NOP a,x", 0x3C),
            new("AND a,x", 0x3D),
            new("ROL a,x", 0x3E),
            new("RLA a,x", 0x3F),
            // $40
            new("RTI", 0x40),
            new("EOR (d,x)", 0x41),
            new("STP", 0x42),
            new("SRE (d,x)", 0x43),
            new("NOP d", 0x44),
            new("EOR d", 0x45),
            new("LSR d", 0x46),
            new("SRE d", 0x47),
            new("PHA", 0x48),
            new("EOR #i", 0x49),
            new("LSR A", 0x4A),
            new("ALR #i", 0x4B),
            new("JMP a", 0x4C),
            new("EOR a", 0x4D),
            new("LSR a", 0x4E),
            new("SRE a", 0x4F),
            // $50
            new("BVC *+d", 0x50),
            new("EOR (d),y", 0x51),
            new("STP", 0x52),
            new("SRE (d),y", 0x53),
            new("NOP d,x", 0x54),
            new("EOR d,x", 0x55),
            new("LSR d,x", 0x56),
            new("SRE d,x", 0x57),
            new("CLI", 0x58),
            new("EOR a,y", 0x59),
            new("NOP", 0x5A),
            new("SRE a,y", 0x5B),
            new("NOP a,x", 0x5C),
            new("EOR a,x", 0x5D),
            new("LSR a,x", 0x5E),
            new("SRE a,x", 0x5F),
            // $60
            new("RTS", 0x60),
            new("ADC (d,x)", 0x61),
            new("STP", 0x62),
            new("RRA (d,x)", 0x63),
            new("NOP d", 0x64),
            new("ADC d", 0x65),
            new("ROR d", 0x66),
            new("RRA d", 0x67),
            new("PLA", 0x68),
            new("ADC #i", 0x69),
            new("ROR A", 0x6A),
            new("ARR #i", 0x6B),
            new("JMP (a)", 0x6C),
            new("ADC a", 0x6D),
            new("ROR a", 0x6E),
            new("RRA a", 0x6F),
            // $70
            new("BVS *+d", 0x70),
            new("ADC (d),y", 0x71),
            new("STP", 0x72),
            new("RRA (d),y", 0x73),
            new("NOP d,x", 0x74),
            new("ADC d,x", 0x75),
            new("ROR d,x", 0x76),
            new("RRA d,x", 0x77),
            new("SEI", 0x78),
            new("ADC a,y", 0x79),
            new("NOP", 0x7A),
            new("RRA a,y", 0x7B),
            new("NOP a,x", 0x7C),
            new("ADC a,x", 0x7D),
            new("ROR a,x", 0x7E),
            new("RRA a,x", 0x7F),
            // $80
            new("NOP #i", 0x80),
            new("STA (d,x)", 0x81),
            new("NOP #i", 0x82),
            new("SAX (d,x)", 0x83),
            new("STY d", 0x84),
            new("STA d", 0x85),
            new("STX d", 0x86),
            new("SAX d", 0x87),
            new("DEY", 0x88),
            new("NOP #i", 0x89),
            new("TXA", 0x8A),
            new("XAA #i", 0x8B),
            new("STY a", 0x8C),
            new("STA a", 0x8D),
            new("STX a", 0x8E),
            new("SAX a", 0x8F),
            // $90
            new("BCC *+d", 0x90),
            new("STA (d),y", 0x91),
            new("STP", 0x92),
            new("AHX (d),y", 0x93),
            new("STY d,x", 0x94),
            new("STA d,x", 0x95),
            new("STX d,y", 0x96),
            new("SAX d,y", 0x97),
            new("TYA", 0x98),
            new("STA a,y", 0x99),
            new("TXS", 0x9A),
            new("TAS a,y", 0x9B),
            new("SHY a,x", 0x9C),
            new("STA a,x", 0x9D),
            new("SHX a,y", 0x9E),
            new("AHX a,y", 0x9F),
            // $A0
            new("LDY #i", 0xA0),
            new("LDA (d,x)", 0xA1),
            new("LDX #i", 0xA2),
            new("LAX (d,x)", 0xA3),
            new("LDY d", 0xA4),
            new("LDA d", 0xA5),
            new("LDX d", 0xA6),
            new("LAX d", 0xA7),
            new("TAY", 0xA8),
            new("LDA #i", 0xA9),
            new("TAX", 0xAA),
            new("LAX #i", 0xAB),
            new("LDY a", 0xAC),
            new("LDA a", 0xAD),
            new("LDX a", 0xAE),
            new("LAX a", 0xAF),
            // $B0
            new("BCS *+d", 0xB0),
            new("LDA (d),y", 0xB1),
            new("STP", 0xB2),
            new("LAX (d),y", 0xB3),
            new("LDY d,x", 0xB4),
            new("LDA d,x", 0xB5),
            new("LDX d,y", 0xB6),
            new("LAX d,y", 0xB7),
            new("CLV", 0xB8),
            new("LDA a,y", 0xB9),
            new("TSX", 0xBA),
            new("LAS a,y", 0xBB),
            new("LDY a,x", 0xBC),
            new("LDA a,x", 0xBD),
            new("LDX a,y", 0xBE),
            new("LAX a,y", 0xBF),
            // $C0
            new("CPY #i", 0xC0),
            new("CMP (d,x)", 0xC1),
            new("NOP #i", 0xC2),
            new("DCP (d,x)", 0xC3),
            new("CPY d", 0xC4),
            new("CMP d", 0xC5),
            new("DEC d", 0xC6),
            new("DCP d", 0xC7),
            new("INY", 0xC8),
            new("CMP #i", 0xC9),
            new("DEX", 0xCA),
            new("AXS #i", 0xCB),
            new("CPY a", 0xCC),
            new("CMP a", 0xCD),
            new("DEC a", 0xCE),
            new("DCP a", 0xCF),
            // $D0
            new("BNE *+d", 0xD0),
            new("CMP (d),y", 0xD1),
            new("STP", 0xD2),
            new("DCP (d),y", 0xD3),
            new("NOP d,x", 0xD4),
            new("CMP d,x", 0xD5),
            new("DEC d,x", 0xD6),
            new("DCP d,x", 0xD7),
            new("CLD", 0xD8),
            new("CMP a,y", 0xD9),
            new("NOP", 0xDA),
            new("DCP a,y", 0xDB),
            new("NOP a,x", 0xDC),
            new("CMP a,x", 0xDD),
            new("DEC a,x", 0xDE),
            new("DCP a,x", 0xDF),
            // $E0
            new("CPX #i", 0xE0),
            new("SBC (d,x)", 0xE1),
            new("NOP #i", 0xE2),
            new("ISC (d,x)", 0xE3),
            new("CPX d", 0xE4),
            new("SBC d", 0xE5),
            new("INC d", 0xE6),
            new("ISC d", 0xE7),
            new("INX", 0xE8),
            new("SBC #i", 0xE9),
            new("NOP", 0xEA),
            new("SBC #i", 0xEB),
            new("CPX a", 0xEC),
            new("SBC a", 0xED),
            new("INC a", 0xEE),
            new("ISC a", 0xEF),
            // $F0
            new("BEQ *+d", 0xF0),
            new("SBC (d),y", 0xF1),
            new("STP", 0xF2),
            new("ISC (d),y", 0xF3),
            new("NOP d,x", 0xF4),
            new("SBC d,x", 0xF5),
            new("INC d,x", 0xF6),
            new("ISC d,x", 0xF7),
            new("SED", 0xF8),
            new("SBC a,y", 0xF9),
            new("NOP", 0xFA),
            new("ISC a,y", 0xFB),
            new("NOP a,x", 0xFC),
            new("SBC a,x", 0xFD),
            new("INC a,x", 0xFE),
            new("ISC a,x", 0xFF),
        };
    }
}
